config/routes.rb
Rails.application.routes.draw do
  
  resources :inventories

  resources :salesmen

  resources :products

  resources :product_tables

  resources :orders

  resources :customers

end

app/controllers/salesmen_controller.rb
class SalesmenController < ApplicationController
  before_action :set_salesman, only: [:show, :edit, :update, :destroy]

  # GET /salesmen
  # GET /salesmen.json
  def index
    @salesmen = Salesman.all
  end

  # GET /salesmen/1
  # GET /salesmen/1.json
  def show
  end

  # GET /salesmen/new
  def new
    @salesman = Salesman.new
  end

  # GET /salesmen/1/edit
  def edit
  end

  # POST /salesmen
  # POST /salesmen.json
  def create
    @salesman = Salesman.new(salesman_params)

    respond_to do |format|
      if @salesman.save
        format.html { redirect_to @salesman, notice: 'Salesman was successfully created.' }
        format.json { render :show, status: :created, location: @salesman }
      else
        format.html { render :new }
        format.json { render json: @salesman.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salesmen/1
  # PATCH/PUT /salesmen/1.json
  def update
    respond_to do |format|
      if @salesman.update(salesman_params)
        format.html { redirect_to @salesman, notice: 'Salesman was successfully updated.' }
        format.json { render :show, status: :ok, location: @salesman }
      else
        format.html { render :edit }
        format.json { render json: @salesman.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salesmen/1
  # DELETE /salesmen/1.json
  def destroy
    @salesman.destroy
    respond_to do |format|
      format.html { redirect_to salesmen_url, notice: 'Salesman was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salesman
      @salesman = Salesman.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salesman_params
      params.require(:salesman).permit(:salesmanName, :salesmanmobilenumber, :salesmanid, :salesmanAddress, :salesManarea)
    end
end

app/helpers/salesmen_helper.rb
module SalesmenHelper
end

app/views/salesmen/_form.html.erb
<%= form_for(@salesman) do |f| %>
  <% if @salesman.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salesman.errors.count, "error") %> prohibited this salesman from being saved:</h2>

      <ul>
      <% @salesman.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :salesmanName %><br>
    <%= f.text_area :salesmanName %>
  </div>
  <div class="field">
    <%= f.label :salesmanid %><br>
    <%= f.text_field :salesmanid %>
  </div>
  <div class="field">
    <%= f.label :salesmanAddress %><br>
    <%= f.text_field :salesmanAddress %>
  </div>
  <div class="field">
    <%= f.label :salesManarea %><br>
    <%= f.text_field :salesManarea %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salesmen/edit.html.erb
<h1>Editing Salesman</h1>

<%= render 'form' %>

<%= link_to 'Show', @salesman %> |
<%= link_to 'Back', salesmen_path %>

app/views/salesmen/index.html.erb
<p id="notice"><%= notice %></p>
<body style="background-color:lightgrey">
<h1 align="center"><U>List Of Sales Man<hr></U></h1>
<br> <br><br><br>
<table>
  <thead>
    <tr>
      <th>Salesman Name</th>
      <th>salesmanMobileNumber</th>
      <th>Salesman ID</th>
      <th>Salesman Address</th>
      <th>Salesman Area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salesmen.each do |salesman| %>
      <tr>
        <td><%= salesman.salesmanName %></td>
        <td><%= salesman.salesmanid %></td>
        <td><%= salesman.salesmanAddress %></td>
        <td><%= salesman.salesManarea %></td>
        <td><%= link_to 'Show', salesman %></td>
        <td><%= link_to 'Edit', edit_salesman_path(salesman) %></td>
        <td><%= link_to 'Destroy', salesman, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salesman', new_salesman_path %>
<br>
<%= link_to 'Back Inventory Home', controller: 'inventories' %>

app/views/salesmen/new.html.erb
<h1>New Salesman</h1>

<%= render 'form' %>

<%= link_to 'Back', salesmen_path %>

app/views/salesmen/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Salesmanname:</strong>
  <%= @salesman.salesmanName %>
</p>

<p>
  <strong>Salesmanid:</strong>
  <%= @salesman.salesmanid %>
</p>

<p>
  <strong>Salesmanaddress:</strong>
  <%= @salesman.salesmanAddress %>
</p>

<p>
  <strong>Salesmanarea:</strong>
  <%= @salesman.salesManarea %>
</p>

<%= link_to 'Edit', edit_salesman_path(@salesman) %> |
<%= link_to 'Back', salesmen_path %>